# Библиотеки для АД. NumPy

# Задание 1

Напишите функцию get_nonzero_diag_product(X), которая подсчитывает произведение ненулевых элементов на диагонали прямоугольной матрицы. Если все элементы на диагонали нулевые, функция должна вернуть None.

Функция должна быть написана с использованием библиотеки numpy. Использование циклов категорически запрещено.

In [55]:
import numpy as np


def get_nonzero_diag_product(X):
    d = np.diag(X)
    if any(d != 0):
        return np.prod(d[d != 0])
    else:
        return None

In [56]:
get_nonzero_diag_product(np.array([[1, 0], [0, 0]]))

1

# Задание 2

Охотники за сокровищами отправились за очередным кладом в необычное место, которое называется "Поле чудес". "Поле чудес" имеет размер H на W метров. На каждом квадратном метре "Поля чудес" закопан сундук с определённым количеством камней. Скоро "Поле чудес" должен посетить лепрекон. Под влиянием лепрекона камни в сундуках превращаются в золотые монеты. Лепрекон появляется в определённой клетке поля и действует на прямоугольную область размером h на w, верхний левый край этой области - точка, где стоит лепрекон. Охотники за сокровищами не знают, когда точно появятся лепрекон, но хотят получить как можно больше золота. Известно вероятностное распределение на появление лепрекона в каждый момент времени в каждой клетке поля. Необходимо для каждой клетки "Поля чудес" посчитать математическое ожидание награды, которое будет получено от этой клетки.

Необходимо написать функцию calc_expectations(h, w, X, Q), где:

* h, w - размеры области влияния лепрекона;
* X - матрица целых чисел размера H на W; X[i, j] - количество камней в i, j клетке;
* Q - матрица вещественных чисел размера H на W, задающая вероятностное распределение; Q[i, j] - вероятность появления лепрекона в точке i, j.

Функция возвращает матрицу E размера H на W; E[i, j] – математическое ожидание награды в i, j клетке.

Функция должна быть написана с использованием библиотеки numpy. Использование циклов категорически запрещено.

In [1]:
import numpy as np


def calc_expectations(h, w, X, Q):
    R = np.apply_along_axis(lambda x: np.concatenate(
        [np.cumsum(x[:w - 1]), np.convolve(x, np.ones(w), 'valid')]), axis=1, arr=Q)
    R = np.apply_along_axis(lambda x: np.concatenate(
        [np.cumsum(x[:h - 1]), np.convolve(x, np.ones(h), 'valid')]), axis=0, arr=R)
    return X * R

In [97]:
def calc_expectations(h, w, X, Q):
    Q = np.apply_along_axis(lambda x: np.convolve(x, np.ones(w), mode = 'full'), axis = 1, arr =Q)
    Q = np.apply_along_axis(lambda x: np.convolve(x, np.ones(h), mode = 'full'), axis = 0, arr =Q)
    Q = Q[:X.shape[0], :X.shape[1]]
    return X * Q

# Задание 3

Напишите функцию replace_nan_to_means(X), принимающую матрицу X. Функция должна вернуть копию матрицы X, в которой все значения nan в каждом столбце заменены на среднее арифметическое остальных элементов столбца. В случае столбца из одних nan необходимо заменить все элементы столбца на нули. Исходная матрица X должна остаться неизменной.

Функция должна быть написана с использованием библиотеки numpy. Использование циклов категорически запрещено.

In [235]:
import numpy as np


def replace_nan_to_means(X):
    mask = np.all(np.isnan(X), axis=0)
    X_new = X.copy()
    X_new[:, mask] = 0
    X_new = np.nan_to_num(X_new, copy=False, nan=np.nanmean(X_new, axis=0))
    return X_new

In [506]:
replace_nan_to_means(np.array([[0, 1, 2], [np.nan, 1, np.nan], [5, 6, 7]]))

array([[0. , 1. , 2. ],
       [2.5, 1. , 4.5],
       [5. , 6. , 7. ]])

# Задание 4

Напишите get_max_after_zero(x), возвращающую максимальный элемент в векторе x среди элементов, перед которыми стоит нулевой. Если подходящих элементов нет, функция должна возвращать None.

Функция должна быть написана с использованием библиотеки numpy. Использование циклов категорически запрещено.

In [297]:
import numpy as np


def get_max_after_zero(x):
    if np.all(x != 0):
        return None
    zeroes_ind = np.where(x == 0)[0]
    zeroes_ind = zeroes_ind[zeroes_ind != x.shape[0] - 1]
    if zeroes_ind.shape[0] == 0:
        return None
    return np.max(x[zeroes_ind + 1])

In [504]:
get_max_after_zero(np.array([1, 2, 9, 8, 0, 5]))

5

# Задание 5

Напишите функцию encode_rle(x), реализующую кодирование длин серий (Run-length encoding). По входному вектору x необходимо вернуть кортеж из двух векторов одинаковой длины. Первый содержит числа, а второй — сколько раз их нужно повторить.

Функция должна быть написана с использованием библиотеки numpy. Использование циклов категорически запрещено.

In [500]:
import numpy as np


def encode_rle(x):
    change_ind = np.where(x[:-1] != x[1:])[0] + 1
    change_ind = np.concatenate([[0], change_ind])
    nums = x[change_ind]
    counts = np.diff(np.concatenate([change_ind, [x.shape[0]]]))
    return nums, counts

In [503]:
encode_rle(np.array([0, 0, 1, 1, 1, 2, 1]))

(array([0, 1, 2, 1]), array([2, 3, 1, 1], dtype=int64))

# Задание 6

**Часть 1**

На вход вашей программе подается бинарный файл input.bin, который содержит в себе двумерный numpy-массив. Все элементы в строке массива уникальны.

Напишите программу, которая найдет индексы топ-5 наибольших значений в каждой строке. Индексы должны быть отсортированы в порядке уменьшения значений, хранящихся по этим индексам.

**Часть 2**
Теперь будем полагать, что в файле input.bin хранится N-мерный numpy-массив (N ≥ 2).

Поддержите параметр axis, который указывает, вдоль какой оси должно нужно отбирать индексы. Легко убедиться в том, что в случае N = 2 и axis = 1 имеем базовую формулировку задачи.

## Часть 1

In [1]:
import numpy as np


def get_best_indices(rank, top):
    return np.flip(np.argpartition(rank, np.arange(
        rank.shape[1] - top, rank.shape[1]), axis=1)[:, -top:], axis=1)


# if __name__ == "__main__":
#     with open('input.bin', 'rb') as f_data:
#         ranks = np.load(f_data)
#     indices = get_best_indices(ranks, 5)
#     with open('output.bin', 'wb') as f_data:
#         np.save(f_data, indices)

In [2]:
a = np.array([[16, 10,  3,  8, 14,  5,  6, 18,  4, 17, 12,  2, 19,  1,  0],
       [ 6,  4, 19, 15, 13, 11, 14,  0,  7, 18,  9, 12,  8, 17,  1],
       [ 9, 12,  1,  2, 11, 17, 19,  8, 13, 15, 16, 10,  0, 18,  7]])

In [3]:
get_best_indices(a, top = 5)

array([[12,  7,  9,  0,  4],
       [ 2,  9, 13,  3,  6],
       [ 6, 13,  5, 10,  9]], dtype=int64)

## Часть 2

In [4]:
import numpy as np


def get_best_indices(rank, top, axis=1):
    return np.apply_along_axis(lambda x: np.flip(np.argpartition(x, np.arange(
        x.shape[0] - top, x.shape[0]))[-top:]), axis=axis, arr=rank)


# if __name__ == "__main__":
#     with open('input.bin', 'rb') as f_data:
#         ranks = np.load(f_data)
#     indices = get_best_indices(rank=ranks, top=5)
#     with open('output.bin', 'wb') as f_data:
#         np.save(f_data, indices)

In [23]:
a = np.array([[16, 10,  3,  8, 14,  5,  6, 18,  4, 17, 12,  2, 19,  1,  0],
       [ 6,  4, 19, 15, 13, 11, 14,  0,  7, 18,  9, 12,  8, 17,  1],
       [ 9, 12,  1,  2, 11, 17, 19,  8, 13, 15, 16, 10,  0, 18,  7]])

In [6]:
get_best_indices(a, top = 5, axis = 1)

array([[12,  7,  9,  0,  4],
       [ 2,  9, 13,  3,  6],
       [ 6, 13,  5, 10,  9]], dtype=int64)